//! Display-only star field: naked-eye stars, constellation figures and boundaries.
//!
//! OWNER: star-field agent. CONVENTIONS 13.6: nothing here is ever a direction source
//! for sight reduction, the solver, the planner's navigation candidates or an accuracy
//! claim. No crate on the navigation path may depend on this one; only the adapters,
//! `skyfix-wasm` and `skyfix-cli` (`skyfix sky`), join it with the engine to label
//! constellations (a test in `tests/crate_boundary.rs` holds the line).
//!
//! What is embedded (all of it under `data/`, generated by `tools/starfield/build.py`;
//! provenance in `docs/THIRD_PARTY.md`, section "Star field and constellations"):
//!
//! | data | source | licence |
//! |---|---|---|
//! | 9 095 stars (`stars.bin`) | Yale Bright Star Catalogue, 5th revised ed., as NASA HEASARC's `bsc5p` table | U.S. Government Work |
//! | 252 star names (`names.txt`) | names in common use (IAU WGSN), Nautical Almanac spelling for the 58 navigational stars | facts |
//! | 88 stick figures (`figures.txt`) | drawn by this project | MIT OR Apache-2.0 |
//! | IAU boundaries (`boundaries.txt`) | Delporte (1930), B1875.0 corners | facts, public domain |
//!
//! Modules:
//!
//! - [`catalog`]: the stars, their designations and names;
//! - [`apparent`]: apparent places of date for every star at once, through exactly the
//!   chain `skyfix_ephemeris::frames` uses for the navigational stars;
//! - [`constellations`]: figures, label positions, `constellation_at` and the boundary
//!   polylines for drawing;
//! - [`navigational`]: which catalogue entry each of the 58 navigational stars is.
//!
//! Accuracy (measured, `docs/ACCURACY.md`, "Star field"): apparent places agree with
//! Skyfield to well inside the 0.1' target of CONVENTIONS 13.7, and `constellation_at`
//! agrees with Skyfield's constellation map everywhere except, possibly, within an
//! arcsecond of a boundary.

pub mod apparent;
pub mod catalog;
pub mod constellations;
pub mod navigational;
// --- deepsky agent (expansion programme, 2026-09-24): deep-sky objects, meteor
// showers, the Milky Way, IAU star names, search, extinction and the "tonight"
// ranking. EXPLORER_API.md, "Deep sky"; CONVENTIONS 13.6.
pub mod dso;
pub mod extinction;
pub mod milkyway;
pub mod names;
pub mod observe;
pub mod search;
pub mod showers;
pub mod tonight;
// --- end deepsky ---

use std::sync::OnceLock;

pub use apparent::{apparent_radec_all, apparent_radec_all_into, frame_matrix};
pub use catalog::Catalog;
pub use constellations::{
    BoundaryPolyline, CONSTELLATIONS, Constellation, boundaries_j2000, constellation_at,
    constellation_at_b1875,
};
pub use navigational::NavigationalMatch;

/// Provenance of the star field, one sentence (the `source` field of
/// `starfield_catalog`).
pub const SOURCE: &str = "Yale Bright Star Catalogue, 5th revised edition (Hoffleit & \
     Warren 1991), as served by NASA's HEASARC (table bsc5p); constellation figures \
     drawn by SkyFix Lab; IAU constellation boundaries of Delporte (1930).";

/// Licence of the star field (the `licence` field of `starfield_catalog`).
pub const LICENCE: &str = "U.S. Government Work (public domain); the constellation \
     figures are SkyFix Lab's own (MIT OR Apache-2.0); boundaries and star names are \
     facts.";

/// First instant the star field answers for. The models are validated over 1990-2060
/// (CONVENTIONS 13.7); this wider window is display-only headroom where precession,
/// nutation and linear proper motion are still good to about an arcsecond.
pub const RANGE_START_UTC: &str = "1800-01-01T00:00:00Z";
/// Last instant the star field answers for.
pub const RANGE_END_UTC: &str = "2200-12-31T23:59:59Z";

fn range_start_jd() -> f64 {
    skyfix_core::time::civil_to_jd(1800, 1, 1)
}

fn range_end_jd() -> f64 {
    skyfix_core::time::civil_to_jd(2200, 12, 31) + 86_399.0 / 86_400.0
}

/// Everything that can go wrong. Malformed input only: the embedded data is checked by
/// the tests, so a [`StarfieldError::Data`] in a released build would be a packaging bug.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum StarfieldError {
    #[error("{0} must be a finite number")]
    NotFinite(&'static str),
    #[error("declination {0} deg is outside [-90, 90]")]
    Declination(f64),
    #[error(
        "jd_utc {jd_utc} is outside the star field's range {RANGE_START_UTC} .. {RANGE_END_UTC}"
    )]
    OutOfRange { jd_utc: f64 },
    #[error("star field data: {0}")]
    Data(String),
}

/// Check a time argument: finite and inside [`RANGE_START_UTC`] ..= [`RANGE_END_UTC`].
pub fn check_jd_utc(jd_utc: f64) -> Result<(), StarfieldError> {
    if !jd_utc.is_finite() {
        return Err(StarfieldError::NotFinite("jd_utc"));
    }
    if jd_utc < range_start_jd() || jd_utc > range_end_jd() {
        return Err(StarfieldError::OutOfRange { jd_utc });
    }
    Ok(())
}

/// The whole star field, parsed and prepared once.
pub struct Starfield {
    pub catalog: Catalog,
    pub(crate) motion: apparent::Motion,
    pub constellations: Vec<Constellation>,
    pub(crate) regions: Vec<constellations::Region>,
    pub navigational: Vec<NavigationalMatch>,
}

/// The star field, parsed on first use. An `Err` means the embedded data is malformed,
/// which the crate's tests rule out for every build they pass on.
pub fn starfield() -> Result<&'static Starfield, StarfieldError> {
    static CELL: OnceLock<Result<Starfield, StarfieldError>> = OnceLock::new();
    CELL.get_or_init(load).as_ref().map_err(Clone::clone)
}

fn load() -> Result<Starfield, StarfieldError> {
    let mut catalog = catalog::parse()?;
    // deepsky: the IAU WGSN names the star field's own list does not have.
    names::extend(&mut catalog)?;
    let motion = apparent::Motion::new(&catalog);
    let regions = constellations::parse_regions()?;
    let constellations = constellations::parse_figures(&catalog)?;
    let navigational = navigational::cross_identify(&catalog)?;
    Ok(Starfield {
        catalog,
        motion,
        constellations,
        regions,
        navigational,
    })
}

/// The catalogue: stars in HR order with designations and names.
pub fn catalog() -> Result<&'static Catalog, StarfieldError> {
    Ok(&starfield()?.catalog)
}

/// The 88 constellations in IAU order, with their figures and label positions.
pub fn constellations() -> Result<&'static [Constellation], StarfieldError> {
    Ok(&starfield()?.constellations)
}

/// The 58 navigational stars (57 Nautical Almanac stars and Polaris) with their index in
/// the catalogue, in `skyfix_ephemeris::catalog` order.
pub fn navigational() -> Result<&'static [NavigationalMatch], StarfieldError> {
    Ok(&starfield()?.navigational)
}
