"""Generate crates/skyfix-geomag/src/coeffs.rs from the published coefficient files.

Development-time only (standard-library Python 3). Reads, from crates/skyfix-geomag/data/:

  WMM2025.COF        NOAA NCEI / BGS, public domain (U.S. Government work)
  igrf14coeffs.txt   IAGA, CC BY 4.0 (Zenodo 10.5281/zenodo.14012302)

and writes the same numbers as compact integer tables (about 11 KB in the binary):

  WMM2025      90 rows (n = 1..12, m = 0..n): g, h, g_dot, h_dot in 0.1 nT and 0.1 nT/yr
  IGRF14_OLD   epochs 1900.0-1995.0 (20), degree 10 (120 rows in file order), whole nT
  IGRF14_NEW   epochs 2000.0-2025.0 (6), degree 13 (195 rows), 0.01 nT
  IGRF14_SV    2025-2030 secular variation, 195 rows, 0.1 nT/yr

The file order of igrf14coeffs.txt is: for n = 1..13, for m = 0..n: the g row, then the
h row when m > 0. The crate's test `the_tables_are_the_published_files` re-parses both
files and compares every number, so a hand edit of coeffs.rs cannot go unnoticed.

Usage, from the repository root:  python3 -m tools.geomag.gen_coeffs
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "crates" / "skyfix-geomag" / "data"
OUT = ROOT / "crates" / "skyfix-geomag" / "src" / "coeffs.rs"


def scaled(text: str, factor: int) -> int:
    v = Decimal(text) * factor
    if v != v.to_integral_value():
        raise SystemExit(f"{text} is not a multiple of 1/{factor}")
    return int(v)


def wmm_rows() -> list[tuple[int, int, int, int]]:
    lines = (DATA / "WMM2025.COF").read_text().splitlines()
    head = lines[0].split()
    assert head[0] == "2025.0" and head[1] == "WMM-2025", head
    rows = []
    expect = [(n, m) for n in range(1, 13) for m in range(0, n + 1)]
    for line in lines[1:]:
        f = line.split()
        if not f or f[0].startswith("9999"):
            break
        n, m = int(f[0]), int(f[1])
        assert (n, m) == expect[len(rows)], (n, m)
        rows.append(tuple(scaled(v, 10) for v in f[2:6]))
    assert len(rows) == 90
    return rows


def igrf_rows() -> tuple[list[str], list[list[str]]]:
    header = None
    rows = []
    for line in (DATA / "igrf14coeffs.txt").read_text().splitlines():
        if line.startswith("g/h"):
            header = line.split()
        elif line[:2] in ("g ", "h "):
            rows.append(line.split())
    assert header is not None
    epochs = header[3:-1]
    assert epochs == [f"{y}.0" for y in range(1900, 2030, 5)], epochs
    assert header[-1] == "2025-30"
    order = []
    for n in range(1, 14):
        for m in range(0, n + 1):
            order.append(("g", n, m))
            if m > 0:
                order.append(("h", n, m))
    assert [(r[0], int(r[1]), int(r[2])) for r in rows] == order
    return epochs, rows


def rust_rows(rows, width: int) -> str:
    out = []
    for r in rows:
        out.append("    [" + ", ".join(f"{v:>{width}}" for v in r) + "],")
    return "\n".join(out)


def main() -> None:
    wmm = wmm_rows()
    epochs, rows = igrf_rows()
    old = []  # 1900..1995: 20 epochs, n <= 10, whole nT
    for r in rows[:120]:
        assert int(r[1]) <= 10
        old.append([scaled(v, 1) for v in r[3:23]])
    for r in rows[120:]:
        assert all(Decimal(v) == 0 for v in r[3:23]), r[:3]
    for r in old:
        assert all(-32768 <= v <= 32767 for v in r)
    new = [[scaled(v, 100) for v in r[23:29]] for r in rows]  # 2000..2025, 0.01 nT
    sv = [scaled(r[29], 10) for r in rows]  # 0.1 nT/yr
    assert all(-32768 <= v <= 32767 for v in sv)

    text = f"""//! GENERATED by `tools/geomag/gen_coeffs.py` from `crates/skyfix-geomag/data/`. Do not edit:
//! `tests::the_tables_are_the_published_files` re-parses both files and compares every number.
//!
//! - `WMM2025.COF` (header `2025.0 WMM-2025 11/13/2024`): the World Magnetic Model 2025 of NOAA
//!   NCEI and the British Geological Survey, a U.S. Government work in the public domain
//!   (NCEI: "The WMM source code is in the public domain and not licensed or under copyright").
//! - `igrf14coeffs.txt`: the International Geomagnetic Reference Field, 14th generation, by the
//!   International Association of Geomagnetism and Aeronomy (IAGA), 2024, published under
//!   CC BY 4.0 (<https://doi.org/10.5281/zenodo.14012302>); described in Beggan et al.,
//!   "International geomagnetic reference field: the fourteenth generation", Earth Planets
//!   Space 78, 127 (2026), <https://doi.org/10.1186/s40623-025-02360-0>. Converted to
//!   integers without changing any value. Credited in `docs/THIRD_PARTY.md`.

/// Reference epoch of WMM2025, decimal year.
pub(crate) const WMM2025_EPOCH: f64 = 2025.0;

/// WMM2025, rows in (n, m) order for n = 1..=12, m = 0..=n: `[g, h, g_dot, h_dot]` in
/// units of 0.1 nT and 0.1 nT per year.
#[rustfmt::skip]
pub(crate) static WMM2025: [[i32; 4]; 90] = [
{rust_rows(wmm, 7)}
];

/// First IGRF-14 epoch, decimal year; epochs are 5 years apart.
pub(crate) const IGRF14_FIRST_EPOCH: f64 = 1900.0;

/// IGRF-14 at 1900.0, 1905.0, ... 1995.0 (20 epochs), degree 10: the first 120 rows of the
/// file order (for n, for m: g, then h when m > 0), whole nT.
#[rustfmt::skip]
pub(crate) static IGRF14_OLD: [[i16; 20]; 120] = [
{rust_rows(old, 6)}
];

/// IGRF-14 at 2000.0, 2005.0, ... 2025.0 (6 epochs), degree 13: all 195 rows in file order,
/// in units of 0.01 nT.
#[rustfmt::skip]
pub(crate) static IGRF14_NEW: [[i32; 6]; 195] = [
{rust_rows(new, 9)}
];

/// IGRF-14 predictive secular variation for 2025.0-2030.0, 195 rows in file order, in
/// units of 0.1 nT per year (zero above degree 8).
#[rustfmt::skip]
pub(crate) static IGRF14_SV: [i16; 195] = [
{chr(10).join('    ' + ', '.join(f'{v:>4}' for v in sv[i:i + 13]) + ',' for i in range(0, 195, 13))}
];
"""
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
