//! Generates and then guards the inputs the explorer commands' tests and worked examples
//! use. OWNER: cli agent.
//!
//! Like `tests/fixtures.rs`, these files are committed so `docs/CLI.md` can quote real
//! output, and derived rather than typed: every session here is a transcription of an
//! independent reference, never of this project's own output (CONVENTIONS section 11).
//!
//! - `fixtures/reference/nav_methods.json` (Skyfield + JPL DE421, generated by
//!   `tools/reference/gen_nav_methods.py`): noise-free raw sextant readings with a known
//!   truth, for the noon sight, averaging and the running fix;
//! - `fixtures/reference/bowditch_worked_examples.json` (typed from Bowditch, NGA Pub. 9,
//!   2019, sections 1910 and 1912): a single noon altitude and a Polaris sight;
//! - the `lunar_distance` example of `docs/EXPLORER_API.md` (case `lunar-19` of
//!   `fixtures/reference/lunar_distances.json`), copied verbatim.
//!
//! To regenerate after a deliberate change:
//!
//! ```text
//! SKYFIX_WRITE_FIXTURES=1 cargo test -p skyfix-cli --test explorer_fixtures
//! ```

mod support;

use serde_json::{Value, json};
use skyfix_ephemeris::AstroProvider;
use support::data_file;

const NAV: &str = include_str!("../../../fixtures/reference/nav_methods.json");
const BOOK: &str = include_str!("../../../fixtures/reference/bowditch_worked_examples.json");
const API: &str = include_str!("../../../docs/EXPLORER_API.md");

fn nav() -> Value {
    serde_json::from_str(NAV).expect("nav_methods.json is JSON")
}

fn case(section: &str, name: &str) -> Value {
    nav()[section]
        .as_array()
        .expect("a list of cases")
        .iter()
        .find(|c| c["name"] == name)
        .unwrap_or_else(|| panic!("nav_methods.json has no {section} case {name}"))
        .clone()
}

fn book(name: &str) -> Value {
    let doc: Value = serde_json::from_str(BOOK).expect("the Bowditch fixture is JSON");
    doc["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .find(|c| c["name"] == name)
        .unwrap_or_else(|| panic!("no Bowditch case {name}"))
        .clone()
}

/// A session of raw sextant readings from a nav_methods case, with the generator's
/// observer and instrument and the case's DR as the assumed position.
fn sextant_session(c: &Value, name: &str, notes: &str, body: Option<&str>) -> String {
    let o = &nav()["generator"]["observer_for_sextant_readings"];
    let observations: Vec<Value> = c["sights"]
        .as_array()
        .expect("sights")
        .iter()
        .map(|s| {
            json!({
                "id": s["id"],
                "body": body.map_or_else(|| s["body"].clone(), |b| json!(b)),
                "utc": s["utc"],
                "altitude_deg": s["hs_deg"],
                "altitude_kind": "sextant_hs",
                "sigma_arcmin": 0.5,
                "limb": s["limb"],
            })
        })
        .collect();
    let mut observer = json!({
        "height_of_eye_m": o["height_of_eye_m"],
        "pressure_hpa": o["pressure_hpa"],
        "temperature_c": o["temperature_c"],
    });
    if c["dr"].is_object() {
        observer["assumed_position"] =
            json!({"lat_deg": c["dr"]["lat_deg"], "lon_deg": c["dr"]["lon_deg"]});
        observer["assumed_position_role"] = json!({"role": "initializer"});
    }
    canonical(json!({
        "schema": "skyfix.session/1",
        "meta": {"name": name, "notes": notes, "kind": "simulated"},
        "observer": observer,
        "instrument": {
            "name": "simulated sextant",
            "index_correction_arcmin": o["index_correction_arcmin"],
            "horizon": o["horizon"],
        },
        "observations": observations,
    }))
}

/// Parse through the core's own session codec and write it back out, so the committed
/// file is exactly what `skyfix convert` would write for it.
fn canonical(v: Value) -> String {
    let (mut session, _) =
        skyfix_core::session::parse_session(&v.to_string()).expect("the fixture is a session");
    // The fixtures' truths were computed with UT1 = UTC (Skyfield; Bowditch's worked
    // examples know no DUT1), so the sessions say so; otherwise the engine's IERS DUT1
    // would apply (CONVENTIONS 15.2).
    session.clock.dut1_s.get_or_insert(0.0);
    support::to_json(&session)
}

fn noon_equinox() -> String {
    sextant_session(
        &case("noon", "philadelphia-equinox-sun"),
        "Philadelphia equinox noon, 21 Sun sights",
        "Transcribed from fixtures/reference/nav_methods.json (Skyfield, case \
         philadelphia-equinox-sun): 21 noise-free lower-limb sextant readings every two \
         minutes over +/-20 minutes of meridian passage at Philadelphia City Hall. The \
         assumed position is the case's DR, 12 NM from the truth. The truth lives in the \
         reference fixture and nowhere here.",
        Some("Sun"),
    )
}

fn average_vega() -> String {
    sextant_session(
        &case("averaging", "vega-run-philadelphia"),
        "Vega, seven sights over three minutes",
        "Transcribed from fixtures/reference/nav_methods.json (Skyfield, case \
         vega-run-philadelphia): seven noise-free sextant readings of Vega setting over \
         Philadelphia, stationary. The assumed position is the case's DR, 15 NM from the \
         truth.",
        Some("Vega"),
    )
}

/// The running-fix case stores each star only by its direction: name it from the
/// catalogue by declination, as `crates/skyfix-wasm/src/nav.rs` does.
fn running_fix_north() -> String {
    let mut c = case("running_fix", "due-north-12kn");
    let stars = skyfix_ephemeris::stars::StarProvider::new();
    for s in c["sights"].as_array_mut().expect("sights") {
        let dec = s["dec_deg"].as_f64().expect("dec");
        let jd = s["jd_utc"].as_f64().expect("jd");
        let name = skyfix_ephemeris::catalog::names()
            .into_iter()
            .find(|n| {
                stars
                    .geocentric(n, jd)
                    .is_ok_and(|d| (d.dec_deg - dec).abs() < 0.01)
            })
            .expect("a catalogue star has this declination");
        s["body"] = json!(name);
    }
    sextant_session(
        &c,
        "Running fix, three stars an hour and a half apart, 12 kn due north",
        "Transcribed from fixtures/reference/nav_methods.json (Skyfield, case \
         due-north-12kn): three noise-free star sights taken 1.5 hours apart from a vessel \
         making 12 knots due north from 00:00Z. No assumed position: the running fix finds \
         its own linearisation point.",
        None,
    )
}

fn bowditch_1910() -> String {
    let b = book("bowditch-1910-lan");
    let i = &b["input"];
    canonical(json!({
        "schema": "skyfix.session/1",
        "meta": {
            "name": "Bowditch 1910: latitude at local apparent noon",
            "notes": "Typed from Bowditch, NGA Pub. 9 (2019), section 1910, via \
                      fixtures/reference/bowditch_worked_examples.json: 9 March 2016, LAN at \
                      12-08-04 zone time (ZD +3), Hs 45 54.0' lower limb, IC +0.2', height of \
                      eye 68 ft. DR 39 49.0' N, 044 33.0' W, on 045 at 10 knots. The book's \
                      answer is 39 48.6' N.",
            "kind": "real",
        },
        "observer": {
            "height_of_eye_m": i["height_of_eye_m"],
            "assumed_position": {"lat_deg": i["dr_lat_deg"], "lon_deg": i["dr_lon_deg"]},
            "assumed_position_role": {"role": "initializer"},
        },
        "instrument": {
            "name": "",
            "index_correction_arcmin": i["index_correction_arcmin"],
            "horizon": "sea",
        },
        "observations": [{
            "id": "lan",
            "body": "Sun",
            "utc": i["utc"],
            "altitude_deg": i["hs_deg"],
            "altitude_kind": "sextant_hs",
            "sigma_arcmin": 0.2,
            "limb": i["limb"],
        }],
    }))
}

fn bowditch_1912() -> String {
    let b = book("bowditch-1912-polaris");
    let i = &b["input"];
    canonical(json!({
        "schema": "skyfix.session/1",
        "meta": {
            "name": "Bowditch 1912: latitude by Polaris",
            "notes": "Typed from Bowditch, NGA Pub. 9 (2019), section 1912, via \
                      fixtures/reference/bowditch_worked_examples.json: 22 March 2016 at \
                      23-18-56 UT, DR 40 46.0' N, 043 22.0' W, observed altitude of Polaris \
                      40 52.1'. The book's answer is 40 48.4' N.",
            "kind": "real",
        },
        "observer": {
            "assumed_position": {"lat_deg": i["dr_lat_deg"], "lon_deg": i["dr_lon_deg"]},
            "assumed_position_role": {"role": "initializer"},
        },
        "observations": [{
            "id": "polaris",
            "body": "Polaris",
            "utc": i["utc"],
            "altitude_deg": i["ho_deg"],
            "altitude_kind": "observed_ho",
            "sigma_arcmin": 0.2,
        }],
    }))
}

/// The `lunar_distance` example document of docs/EXPLORER_API.md, verbatim.
fn lunar_19() -> String {
    let at = API
        .find("\"utc_estimate\": \"2029-10-17T01:05:43Z\"")
        .expect("EXPLORER_API.md carries the lunar_distance example");
    let open = API[..at].rfind("```json").expect("an opening fence") + "```json".len();
    let close = open + API[open..].find("```").expect("a closing fence");
    let v: Value = serde_json::from_str(&API[open..close]).expect("the example is JSON");
    let mut s = serde_json::to_string_pretty(&v).expect("serialises");
    s.push('\n');
    s
}

/// Everything above is a transcription, so the files must match to the last digit;
/// the tolerance only forgives how `f64` prints.
const NUMERIC_TOLERANCE: f64 = 1e-12;

#[test]
fn committed_explorer_inputs_match_their_sources() {
    let wanted: Vec<(&str, String)> = vec![
        ("noon_equinox_sun.session.json", noon_equinox()),
        ("noon_bowditch_1910.session.json", bowditch_1910()),
        ("polaris_bowditch_1912.session.json", bowditch_1912()),
        ("average_vega.session.json", average_vega()),
        ("running_fix_north.session.json", running_fix_north()),
        ("lunar_19.input.json", lunar_19()),
    ];
    let write = std::env::var("SKYFIX_WRITE_FIXTURES").is_ok();
    for (name, text) in wanted {
        let path = data_file(name);
        if write {
            std::fs::write(&path, &text).expect("tests/data is writable");
            continue;
        }
        let found = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "cannot read {}: {e}. Regenerate with SKYFIX_WRITE_FIXTURES=1 cargo test -p \
                 skyfix-cli --test explorer_fixtures",
                path.display()
            )
        });
        let committed: Value = serde_json::from_str(&found).expect("committed JSON");
        let generated: Value = serde_json::from_str(&text).expect("generated JSON");
        if let Err(what) = support::json_close(&committed, &generated, NUMERIC_TOLERANCE, name) {
            panic!(
                "{} has drifted from its source: {what}. Regenerate with \
                 SKYFIX_WRITE_FIXTURES=1 and re-check docs/CLI.md",
                path.display()
            );
        }
    }
}
