//! Events against the Skyfield + JPL DE440s reference (CONVENTIONS 13.7).
//!
//! `fixtures/reference/events_{sun,stars,moon_planets}.json` are generated by
//! `tools/reference/gen_events.py` with the definitions of CONVENTIONS 13.3 and 13.4
//! coded from the text (never from this crate's output, CONVENTIONS 11). Target: every
//! rise, set, twilight and transit within **10 s** of the reference with the same `h0`.
//!
//! Matching: events are paired kind by kind with the nearest reference event. The
//! reference searches on a one-minute grid, so a body that grazes its threshold for
//! less than a minute can be missing from it while this crate (which inserts every
//! altitude extremum) finds it, or the reverse at the sub-arcsecond level. An unmatched
//! event is accepted only as half of an opposite pair (rise + set, dawn + dusk) less
//! than 15 minutes apart on the same side — a graze — and every such case is printed.
//!
//! The Moon and planet windows need the real providers: while those are stubs the
//! tests **skip loudly**. The synthetic Moon of `common` is compared with the real
//! Moon's events too, loosely, as a check of the definitions (h0 = -34' - SD,
//! topocentric parallax), not of accuracy.

mod common;

use common::{SyntheticSky, load_fixture, site_of, skip_if_stub};
use serde_json::Value;
use skyfix_almanac::events::{DayEvents, EventOptions, day_events};
use skyfix_core::time::format_utc;
use skyfix_ephemeris::body::{BodyEphemeris, Sky};

const SEC: f64 = 1.0 / 86_400.0;

#[derive(Default)]
struct Stats {
    events: usize,
    windows: usize,
    worst_s: f64,
    worst_where: String,
    grazes: Vec<String>,
    by_kind: std::collections::BTreeMap<String, (usize, f64)>,
}

impl Stats {
    fn report(&self, what: &str) -> String {
        let kinds: Vec<String> = self
            .by_kind
            .iter()
            .map(|(k, (n, w))| format!("{k} {n} (worst {w:.3} s)"))
            .collect();
        format!(
            "{what}: {} events in {} windows, worst {:.3} s at {}; {} grazing pairs \
             unmatched{}\n  {}",
            self.events,
            self.windows,
            self.worst_s,
            self.worst_where,
            self.grazes.len(),
            if self.grazes.is_empty() {
                String::new()
            } else {
                format!(": {}", self.grazes.join("; "))
            },
            kinds.join(", ")
        )
    }
}

fn opposite(kind: &str) -> &'static str {
    match kind {
        "rise" => "set",
        "set" => "rise",
        "civil_dawn" => "civil_dusk",
        "civil_dusk" => "civil_dawn",
        "nautical_dawn" => "nautical_dusk",
        "nautical_dusk" => "nautical_dawn",
        "astronomical_dawn" => "astronomical_dusk",
        "astronomical_dusk" => "astronomical_dawn",
        _ => "",
    }
}

/// Unmatched events must pair up into grazes (opposite kinds < 15 min apart).
fn grazes(unmatched: &[(String, f64)]) -> Result<Vec<(String, f64)>, String> {
    let mut left: Vec<(String, f64)> = unmatched.to_vec();
    let mut pairs = Vec::new();
    while let Some((k, t)) = left.pop() {
        let opp = opposite(&k);
        match left
            .iter()
            .position(|(k2, t2)| k2 == opp && (t2 - t).abs() < 15.0 * 60.0 * SEC)
        {
            Some(i) => {
                left.remove(i);
                pairs.push((k, t));
            }
            None => return Err(format!("{k} at {} has no counterpart", format_utc(t))),
        }
    }
    Ok(pairs)
}

/// Compare one window's events; `false` when a graze made the event sets differ.
fn compare(ours: &[(String, f64)], theirs: &[(String, f64)], what: &str, s: &mut Stats) -> bool {
    let mut kinds: Vec<&str> = ours.iter().chain(theirs).map(|(k, _)| k.as_str()).collect();
    kinds.sort_unstable();
    kinds.dedup();
    let mut un_ours = Vec::new();
    let mut un_theirs = Vec::new();
    for kind in kinds {
        let a: Vec<f64> = ours.iter().filter(|e| e.0 == kind).map(|e| e.1).collect();
        let mut b: Vec<Option<f64>> = theirs
            .iter()
            .filter(|e| e.0 == kind)
            .map(|e| Some(e.1))
            .collect();
        for &ta in &a {
            let best = b
                .iter()
                .enumerate()
                .filter_map(|(i, tb)| tb.map(|tb| (i, (tb - ta).abs())))
                .min_by(|x, y| x.1.total_cmp(&y.1));
            match best {
                Some((i, d)) if d < 120.0 * SEC => {
                    b[i] = None;
                    let d_s = d / SEC;
                    s.events += 1;
                    let e = s.by_kind.entry(kind.to_string()).or_default();
                    e.0 += 1;
                    e.1 = e.1.max(d_s);
                    if d_s > s.worst_s {
                        s.worst_s = d_s;
                        s.worst_where = format!("{what} {kind} {}", format_utc(ta));
                    }
                }
                _ => un_ours.push((kind.to_string(), ta)),
            }
        }
        un_theirs.extend(b.into_iter().flatten().map(|t| (kind.to_string(), t)));
    }
    for (side, un) in [
        ("only here", &un_ours),
        ("only in the reference", &un_theirs),
    ] {
        match grazes(un) {
            Ok(p) => {
                for (k, t) in p {
                    s.grazes.push(format!(
                        "{what} {k}/{} {} ({side})",
                        opposite(&k),
                        format_utc(t)
                    ));
                }
            }
            Err(e) => panic!("{what}: {e} ({side}); ours {ours:?}, reference {theirs:?}"),
        }
    }
    un_ours.is_empty() && un_theirs.is_empty()
}

fn fixture_events(w: &Value) -> Vec<(String, f64)> {
    w["events"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| (e[0].as_str().unwrap().to_string(), e[1].as_f64().unwrap()))
        .collect()
}

fn our_events(d: &DayEvents, body: &str) -> Vec<(String, f64)> {
    let b = d.bodies.iter().find(|b| b.body == body).unwrap();
    b.events
        .iter()
        .map(|e| {
            let k = serde_json::to_value(e.kind).unwrap();
            (k.as_str().unwrap().to_string(), e.jd_utc)
        })
        .collect()
}

fn sites(doc: &Value) -> std::collections::HashMap<String, Value> {
    doc["generator"]["sites"]
        .as_array()
        .unwrap()
        .iter()
        .map(|s| (s["name"].as_str().unwrap().to_string(), s.clone()))
        .collect()
}

/// Run every window of a fixture for the bodies it names; returns the statistics.
fn run(
    eph: &dyn BodyEphemeris,
    doc: &Value,
    filter: impl Fn(&Value) -> bool,
    check_phases: bool,
) -> Stats {
    let sites = sites(doc);
    let mut s = Stats::default();
    for w in doc["windows"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|w| filter(w))
    {
        let body = w["body"].as_str().unwrap_or("Sun");
        let site = site_of(&sites[w["site"].as_str().unwrap()]);
        let (t0, t1) = (
            w["jd_start"].as_f64().unwrap(),
            w["jd_end"].as_f64().unwrap(),
        );
        let what = format!("{body} {} {}", w["site"].as_str().unwrap(), w["date"]);
        let d = day_events(eph, &site, t0, t1, &[body], &EventOptions::default())
            .unwrap_or_else(|e| panic!("{what}: {e}"));
        assert!(d.errors.is_empty(), "{what}: {:?}", d.errors);
        s.windows += 1;
        let clean = compare(&our_events(&d, body), &fixture_events(w), &what, &mut s);
        let b = &d.bodies[0];
        if clean {
            assert_eq!(
                b.always_above,
                w["always_above"].as_bool().unwrap(),
                "{what}"
            );
            assert_eq!(
                b.always_below,
                w["always_below"].as_bool().unwrap(),
                "{what}"
            );
        }
        if check_phases && clean {
            let want = w["day_length_h"].as_f64().unwrap();
            let got = b.day_length_h.unwrap();
            assert!(
                (got - want).abs() * 3600.0 < 20.0,
                "{what}: day {got} h vs {want} h"
            );
            // The reference lists the phase names; each bound between two phases is
            // one of its Sun events (rise/set or a twilight).
            let names: Vec<Value> = d
                .phases
                .iter()
                .map(|p| serde_json::to_value(p.phase).unwrap())
                .collect();
            assert_eq!(&names, w["phases"].as_array().unwrap(), "{what}");
            let bounds: Vec<f64> = fixture_events(w)
                .into_iter()
                .filter(|e| e.0 != "transit" && e.0 != "lower_transit")
                .map(|e| e.1)
                .collect();
            for p in &d.phases[1..] {
                let near = bounds
                    .iter()
                    .map(|t| (t - p.jd_start).abs() / SEC)
                    .fold(f64::INFINITY, f64::min);
                assert!(
                    near < 10.0,
                    "{what}: phase bound {near} s from the reference"
                );
            }
        }
    }
    s
}

#[test]
fn sun_rise_set_transit_twilight_and_phases_match_skyfield_within_10_s() {
    let doc = load_fixture("events_sun.json");
    let s = run(&Sky::new(), &doc, |_| true, true);
    eprintln!("{}", s.report("Sun vs Skyfield/DE440s"));
    assert!(
        s.windows >= 600 && s.events > 5000,
        "{} {}",
        s.windows,
        s.events
    );
    assert!(
        s.worst_s < 10.0,
        "worst {} s at {}",
        s.worst_s,
        s.worst_where
    );
}

#[test]
fn star_rise_set_and_transits_match_skyfield_within_10_s() {
    let doc = load_fixture("events_stars.json");
    let s = run(&Sky::new(), &doc, |_| true, false);
    eprintln!("{}", s.report("stars vs Skyfield/DE440s"));
    assert!(s.windows >= 700, "{}", s.windows);
    assert!(
        s.worst_s < 10.0,
        "worst {} s at {}",
        s.worst_s,
        s.worst_where
    );
}

#[test]
fn moon_rise_set_and_transits_match_skyfield_within_10_s() {
    let doc = load_fixture("events_moon_planets.json");
    let jd = doc["windows"][0]["jd_start"].as_f64().unwrap();
    if skip_if_stub(
        "Moon",
        jd,
        "moon_rise_set_and_transits_match_skyfield_within_10_s",
    ) {
        return;
    }
    let s = run(&Sky::new(), &doc, |w| w["body"] == "Moon", false);
    eprintln!("{}", s.report("Moon vs Skyfield/DE440s"));
    assert!(
        s.worst_s < 10.0,
        "worst {} s at {}",
        s.worst_s,
        s.worst_where
    );
}

#[test]
fn planet_rise_set_and_transits_match_skyfield_within_10_s() {
    let doc = load_fixture("events_moon_planets.json");
    let jd = doc["windows"][0]["jd_start"].as_f64().unwrap();
    if skip_if_stub(
        "Venus",
        jd,
        "planet_rise_set_and_transits_match_skyfield_within_10_s",
    ) {
        return;
    }
    let s = run(&Sky::new(), &doc, |w| w["body"] != "Moon", false);
    eprintln!("{}", s.report("planets vs Skyfield/DE440s"));
    assert!(
        s.worst_s < 10.0,
        "worst {} s at {}",
        s.worst_s,
        s.worst_where
    );
}

/// The synthetic test Moon is good to a few hundredths of a degree, so its events are
/// within a minute or two of the real Moon's at mid-latitudes. That is enough to
/// prove the definitions are the reference's: leaving out the parallax (57') would
/// move a moonrise by about five minutes, and leaving out the semidiameter by one.
#[test]
fn the_synthetic_moon_lands_near_the_reference_moon_so_the_definitions_agree() {
    let doc = load_fixture("events_moon_planets.json");
    let sites = sites(&doc);
    let eph = SyntheticSky::new();
    let (mut n, mut worst, mut worst_rs) = (0, 0.0f64, 0.0f64);
    for w in doc["windows"].as_array().unwrap() {
        if w["body"] != "Moon" {
            continue;
        }
        let site = site_of(&sites[w["site"].as_str().unwrap()]);
        if site.lat_deg.abs() > 45.0 {
            continue;
        }
        let (t0, t1) = (
            w["jd_start"].as_f64().unwrap(),
            w["jd_end"].as_f64().unwrap(),
        );
        let d = day_events(&eph, &site, t0, t1, &["Moon"], &EventOptions::default()).unwrap();
        let ours = our_events(&d, "Moon");
        for (k, t) in fixture_events(w) {
            if let Some(d) = ours
                .iter()
                .filter(|e| e.0 == k)
                .map(|e| (e.1 - t).abs() / SEC)
                .min_by(f64::total_cmp)
            {
                if d < 1800.0 {
                    n += 1;
                    worst = worst.max(d);
                    if k == "rise" || k == "set" {
                        worst_rs = worst_rs.max(d);
                    }
                }
            }
        }
    }
    eprintln!(
        "synthetic Moon vs the DE440s Moon at |lat| <= 45: {n} events, worst {worst:.0} s \
         (rise/set {worst_rs:.0} s)"
    );
    assert!(n > 150, "{n}");
    assert!(
        worst_rs < 150.0,
        "rise/set {worst_rs} s: a definition differs"
    );
}
