//! `skyfix_almanac::sun_tools` against independent references (CONVENTIONS 13.10).
//!
//! - `fixtures/reference/sun_tools_skyfield.json`, generated by
//!   `tools/reference/gen_sun_tools.py` from Skyfield + JPL DE440s with UT1 = UTC by
//!   construction (never from this crate's output, CONVENTIONS 11): the equation of time,
//!   the galactic centre and the Milky Way's arch (found there by brute force along the
//!   galactic equator of Skyfield's own galactic frame), bearing crossings of the Sun and
//!   the Moon, Manhattan's sunset azimuths, an analemma, and the clear-sky formulas of
//!   Reno, Hansen & Stein (2012) evaluated from their printed form.
//! - Meeus, *Astronomical Algorithms* (2nd ed.), example 28.a: the equation of time on
//!   1992 October 13.0 TD is +13m 42.6s (E = 3.427351°).
//!
//! Targets: the equation of time within 1 s, directions within 0.01°, instants within
//! 1 s, formulas to 1e-6. The measured worst cases are printed (`--nocapture`) and
//! recorded in `docs/ACCURACY.md` section 14.

mod common;

use common::load_fixture;
use serde_json::Value;
use skyfix_almanac::sun_tools::alignment::{AlignmentEvent, AlignmentRequest, alignment_days};
use skyfix_almanac::sun_tools::analemma::{AnalemmaRequest, ClockKind, analemma};
use skyfix_almanac::sun_tools::azimuth::{AltitudeBand, find_azimuth};
use skyfix_almanac::sun_tools::eot::{equation_of_time, equation_of_time_s};
use skyfix_almanac::sun_tools::galactic::{CENTRE, galactic_moment};
use skyfix_almanac::sun_tools::solar::{PanelUsed, clear_sky, plane_of_array};
use skyfix_almanac::sun_tools::sunpath::{RiseSetRequest, rise_set_azimuths};
use skyfix_core::units::norm_180;
use skyfix_ephemeris::body::{BodyEphemeris, SUN, Sky};
use skyfix_ephemeris::topocentric::{Site, horizontal};

/// Azimuth and altitude of a body at an instant, from `sky_state`.
trait AzAlt {
    fn sky_state_for(&self, site: &Site, body: &str, jd: f64) -> (f64, f64);
}

impl AzAlt for Sky {
    fn sky_state_for(&self, site: &Site, body: &str, jd: f64) -> (f64, f64) {
        let s = skyfix_almanac::sky::sky_state(self, site, jd, &[body]).unwrap();
        (s.bodies[0].az_deg, s.bodies[0].alt_deg)
    }
}

fn fixture() -> Value {
    load_fixture("sun_tools_skyfield.json")
}

fn num(v: &Value) -> f64 {
    v.as_f64().unwrap_or_else(|| panic!("not a number: {v}"))
}

fn site(v: &Value) -> Site {
    Site {
        height_m: num(&v["height_m"]),
        ..Site::new(num(&v["lat_deg"]), num(&v["lon_deg"]))
    }
}

#[test]
fn equation_of_time_against_skyfield_within_a_second() {
    let fx = fixture();
    let sky = Sky::new();
    let (mut worst_s, mut worst_dec) = (0.0f64, 0.0f64);
    let cases = fx["equation_of_time"].as_array().unwrap();
    for c in cases {
        let jd = num(&c["jd_utc"]);
        let sun = sky.apparent_state(SUN, jd).unwrap();
        let d = equation_of_time_s(&sun) - num(&c["eot_s"]);
        worst_s = worst_s.max(d.abs());
        worst_dec = worst_dec.max((sun.dec_deg - num(&c["sun_dec_deg"])).abs());
    }
    eprintln!(
        "equation of time: {} instants 1990-2060, worst {worst_s:.4} s; Sun Dec worst \
         {:.3}\"",
        cases.len(),
        worst_dec * 3600.0
    );
    assert!(worst_s < 1.0, "worst {worst_s} s");
    // What the Sun provider's validation (0.16" in GHA) implies: about 0.01 s.
    assert!(
        worst_s < 0.05,
        "worst {worst_s} s, far above the Sun's own accuracy"
    );
    assert!(worst_dec < 0.01);
}

#[test]
fn the_yearly_series_is_evaluated_at_the_stated_instants() {
    let fx = fixture();
    let sky = Sky::new();
    let mut checked = 0;
    for year in [1990, 2025, 2060] {
        let series = equation_of_time(&sky, year, 12.0).unwrap();
        assert!(series.errors.is_empty(), "{:?}", series.errors);
        for c in fx["equation_of_time"].as_array().unwrap() {
            let jd = num(&c["jd_utc"]);
            if let Some(p) = series.points.iter().find(|p| (p.jd_utc - jd).abs() < 1e-9) {
                assert!((p.eot_s - num(&c["eot_s"])).abs() < 0.05, "{p:?} {c}");
                checked += 1;
            }
        }
    }
    assert_eq!(
        checked,
        3 * 24,
        "the 1st and 15th of every month at 12h UTC"
    );
}

#[test]
fn equation_of_time_matches_meeus_example_28a() {
    // 1992 October 13.0 TD = JDE 2448908.5; TT - UTC = 32.184 + 27 s then.
    let jd_utc = 2_448_908.5 - (32.184 + 27.0) / 86_400.0;
    let sky = Sky::new();
    let e = equation_of_time_s(&sky.apparent_state(SUN, jd_utc).unwrap());
    let meeus = 3.427_351 * 240.0; // +13m 42.564s
    eprintln!(
        "Meeus 28.a: {meeus:.3} s; this engine {e:.3} s ({:+.3} s)",
        e - meeus
    );
    assert!((e - meeus).abs() < 1.0, "{e} vs {meeus}");
    // Meeus's own route (eq. 28.1, the Sun provider's display helper) runs 0.21 s ahead
    // of the GHA definition by construction; it reproduces the book to its rounding.
    let m = skyfix_ephemeris::sun::equation_of_time_min(jd_utc).unwrap() * 60.0;
    assert!((m - meeus).abs() < 0.1, "{m} vs {meeus}");
    assert!((m - e - 0.21).abs() < 0.02, "{m} - {e}");
}

#[test]
fn galactic_centre_and_arch_against_skyfield() {
    let fx = fixture();
    let (mut w_radec, mut w_alt, mut w_az, mut w_top_alt, mut w_top_az) =
        (0.0f64, 0.0f64, 0.0f64, 0.0f64, 0.0f64);
    let cases = fx["galactic"].as_array().unwrap();
    for c in cases {
        let s = site(c);
        let jd = num(&c["jd_utc"]);
        let st = CENTRE.state(jd);
        let dra = norm_180(st.ra_deg - num(&c["centre_ra_deg"])) * st.dec_deg.to_radians().cos();
        let ddec = st.dec_deg - num(&c["centre_dec_deg"]);
        w_radec = w_radec.max(dra.hypot(ddec));
        let h = horizontal(&st, &s);
        w_alt = w_alt.max((h.alt_deg - num(&c["centre_alt_deg"])).abs());
        if h.alt_deg.abs() < 89.0 {
            let daz = norm_180(h.az_deg - num(&c["centre_az_deg"])) * h.alt_deg.to_radians().cos();
            w_az = w_az.max(daz.abs());
        }
        let m = galactic_moment(&s, jd);
        assert!((m.alt_deg - h.alt_deg).abs() < 1e-12);
        w_top_alt = w_top_alt.max((m.arch_top_alt_deg - num(&c["arch_top_alt_deg"])).abs());
        if m.arch_top_alt_deg < 89.5 {
            let daz = norm_180(m.arch_top_az_deg - num(&c["arch_top_az_deg"]))
                * m.arch_top_alt_deg.to_radians().cos();
            w_top_az = w_top_az.max(daz.abs());
        }
    }
    eprintln!(
        "galactic centre, {} cases at six sites: RA/Dec of date {:.3}\", altitude {:.3}\", \
         azimuth (on the sky) {:.3}\"; arch top against the brute-force search: altitude \
         {:.3}\", azimuth {:.3}\"",
        cases.len(),
        w_radec * 3600.0,
        w_alt * 3600.0,
        w_az * 3600.0,
        w_top_alt * 3600.0,
        w_top_az * 3600.0
    );
    assert!(w_radec < 0.01 && w_alt < 0.01 && w_az < 0.01);
    // The fixture's pole is Skyfield's galactic frame (0.3" from the stated one) and its
    // top is found by golden section to about 0.1".
    assert!(w_top_alt < 0.01 && w_top_az < 0.01);
}

#[test]
fn bearing_crossings_against_skyfield_within_a_second() {
    let fx = fixture();
    let sky = Sky::new();
    let any = AltitudeBand {
        min_deg: Some(-90.0),
        max_deg: Some(90.0),
    };
    let (mut worst_s, mut worst_alt, mut worst_sky) = (0.0f64, 0.0f64, 0.0f64);
    let cases = fx["azimuth_crossings"].as_array().unwrap();
    // Group the reference by case (site, body, bearing, window).
    let mut groups: Vec<(String, Vec<&Value>)> = Vec::new();
    for c in cases {
        let key = format!(
            "{} {} {} {}",
            c["site"], c["body"], c["bearing_deg"], c["window"][0]
        );
        match groups.iter_mut().find(|(k, _)| *k == key) {
            Some((_, v)) => v.push(c),
            None => groups.push((key, vec![c])),
        }
    }
    for (key, refs) in &groups {
        let c = refs[0];
        let s = site(c);
        let got = find_azimuth(
            &sky,
            &s,
            c["body"].as_str().unwrap(),
            num(&c["window"][0]),
            num(&c["window"][1]),
            num(&c["bearing_deg"]),
            &any,
        )
        .unwrap();
        assert_eq!(got.len(), refs.len(), "{key}: {got:?}");
        for (g, r) in got.iter().zip(refs) {
            let dt_s = (g.jd_utc - num(&r["jd_utc"])) * 86_400.0;
            // How fast the bearing is being swept at that instant, degrees of arc on the
            // sky per second: a crossing where the azimuth barely moves (the equinox Sun
            // climbing straight up at Quito) has an ill-conditioned instant, and its
            // honest error is the angle, not the time.
            let az = |t: f64| {
                let st = sky.sky_state_for(&s, c["body"].as_str().unwrap(), t);
                (st.0, st.1)
            };
            let (a0, _) = az(g.jd_utc - 30.0 / 86_400.0);
            let (a1, alt1) = az(g.jd_utc + 30.0 / 86_400.0);
            let rate = norm_180(a1 - a0).abs() / 60.0 * alt1.to_radians().cos();
            let on_sky = dt_s.abs() * rate;
            eprintln!(
                "  {key}: {} dt {dt_s:+.3} s, sweep {:.2} deg/h, on the sky {:.3}\"",
                g.utc,
                rate * 3600.0,
                on_sky * 3600.0
            );
            worst_sky = worst_sky.max(on_sky);
            if rate * 3600.0 > 1.0 {
                worst_s = worst_s.max(dt_s.abs());
            }
            worst_alt =
                worst_alt.max((g.alt_deg - num(&r["alt_deg"])).abs() - dt_s.abs() * 15.0 / 3600.0);
            assert_eq!(g.clockwise, r["clockwise"].as_bool().unwrap(), "{key}");
        }
    }
    // Quito's afternoon Sun on 21 March sits just north of due west and never crosses 270.
    let quito = Site {
        height_m: 2850.0,
        ..Site::new(-0.1807, -78.4678)
    };
    let d = skyfix_core::time::civil_to_jd(2026, 3, 21);
    assert!(
        find_azimuth(&sky, &quito, "Sun", d, d + 1.0, 270.0, &any)
            .unwrap()
            .is_empty()
    );
    eprintln!(
        "bearing crossings: {} Sun and Moon crossings; on the sky worst {:.3}\"; instants \
         worst {worst_s:.3} s where the bearing is swept faster than 1 deg/h",
        cases.len(),
        worst_sky * 3600.0
    );
    assert!(worst_sky < 0.01 && worst_s < 1.0 && worst_alt < 0.01);
}

#[test]
fn manhattan_sunset_azimuths_against_skyfield() {
    let fx = fx_sets();
    let sky = Sky::new();
    let s = site(&fx["site"]);
    let year = rise_set_azimuths(
        &sky,
        &s,
        &RiseSetRequest {
            body: "Sun".into(),
            year: 2026,
            utc_offset_hours: Some(-4.0),
            options: None,
        },
    )
    .unwrap();
    let (mut worst_s, mut worst_az) = (0.0f64, 0.0f64);
    for r in fx["sets"].as_array().unwrap() {
        let date = r["local_date"].as_str().unwrap();
        let day = year.days.iter().find(|d| d.date == date).unwrap();
        let set = &day.sets[0];
        worst_s = worst_s.max((set.jd_utc - num(&r["jd_utc"])).abs() * 86_400.0);
        worst_az = worst_az.max(norm_180(set.az_deg - num(&r["az_deg"])).abs());
    }
    eprintln!(
        "Manhattan sunsets (h0 = -50'): worst {worst_s:.3} s, azimuth {:.3}\"",
        worst_az * 3600.0
    );
    assert!(worst_s < 1.0 && worst_az < 0.01);
    // The alignment finder reports exactly these sets.
    let a = alignment_days(
        &sky,
        &s,
        &AlignmentRequest {
            body: "Sun".into(),
            year: 2026,
            azimuth_deg: 299.0,
            tolerance_deg: 0.3,
            event: AlignmentEvent::Set,
            utc_offset_hours: Some(-4.0),
            options: None,
        },
    )
    .unwrap();
    for m in &a.matches {
        let day = year.days.iter().find(|d| d.date == m.date).unwrap();
        assert!((day.sets[0].jd_utc - m.jd_utc).abs() < 1e-7, "{m:?}");
        assert!((day.sets[0].az_deg - m.az_deg).abs() < 1e-6, "{m:?}");
    }
}

fn fx_sets() -> Value {
    fixture()["sunset_azimuths"].clone()
}

#[test]
fn analemma_against_skyfield() {
    let fx = fixture()["analemma"].clone();
    let sky = Sky::new();
    let s = site(&fx["site"]);
    let a = analemma(
        &sky,
        &s,
        &AnalemmaRequest {
            year: 2026,
            time_h: 12.0,
            clock: ClockKind::Lmt,
            utc_offset_hours: None,
        },
    )
    .unwrap();
    assert_eq!(a.points.len(), 365);
    let mut worst = 0.0f64;
    for r in fx["points"].as_array().unwrap() {
        let p = a
            .points
            .iter()
            .find(|p| p.date == r["local_date"].as_str().unwrap())
            .unwrap();
        assert!((p.jd_utc - num(&r["jd_utc"])).abs() < 1e-8, "{p:?}");
        worst = worst
            .max((p.alt_deg - num(&r["alt_deg"])).abs())
            .max((norm_180(p.az_deg - num(&r["az_deg"])) * p.alt_deg.to_radians().cos()).abs());
    }
    eprintln!("analemma at 12:00 LMT: worst {:.3}\"", worst * 3600.0);
    assert!(worst < 0.01);
}

#[test]
fn clear_sky_formulas_as_printed() {
    let fx = fixture()["solar_formulas"].clone();
    let mut n = 0;
    for c in fx["clear_sky"].as_array().unwrap() {
        let cs = clear_sky(num(&c["apparent_zenith_deg"]), num(&c["sun_distance_au"]));
        for (got, key) in [
            (cs.ghi_w_m2, "ghi_w_m2"),
            (cs.dni_w_m2, "dni_w_m2"),
            (cs.dhi_w_m2, "dhi_w_m2"),
        ] {
            assert!((got - num(&c[key])).abs() < 1e-5, "{key}: {got} vs {c}");
        }
        n += 1;
    }
    for c in fx["plane_of_array"].as_array().unwrap() {
        let z = num(&c["apparent_zenith_deg"]);
        let cs = clear_sky(z, num(&c["sun_distance_au"]));
        let panel = PanelUsed {
            tilt_deg: num(&c["tilt_deg"]),
            azimuth_deg: num(&c["panel_az_deg"]),
            albedo: num(&c["albedo"]),
        };
        let p = plane_of_array(&cs, z, num(&c["sun_az_deg"]), &panel);
        assert!(
            (p.total_w_m2 - num(&c["poa_w_m2"])).abs() < 1e-5,
            "{p:?} {c}"
        );
        assert!(
            (p.incidence_deg - num(&c["incidence_deg"])).abs() < 1e-5,
            "{p:?} {c}"
        );
        n += 1;
    }
    eprintln!("clear-sky and plane-of-array formulas: {n} cases to 1e-5 W/m2");
}
