//! Apparent places of the display catalogue against Skyfield
//! (`fixtures/reference/starfield_apparent.json`, generated by
//! `tools/starfield/gen_fixtures.py` from the raw HEASARC table with DE440s).
//!
//! CONVENTIONS 13.7: star-field apparent places within 0.1'. The measured worst case is
//! printed (`cargo test -p skyfix-starfield --test apparent_reference -- --nocapture`)
//! and recorded in docs/ACCURACY.md.

use serde_json::Value;

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/reference/starfield_apparent.json"
);

/// The target of CONVENTIONS 13.7, arcseconds.
const TARGET_ARCSEC: f64 = 6.0;
/// A regression guard well under the target: the pipeline's known omissions (radial
/// velocity, up to 0.31" here; the Keplerian Earth, about 0.02") leave it far below.
const GUARD_ARCSEC: f64 = 0.5;

fn load() -> Value {
    let text = std::fs::read_to_string(FIXTURE).expect("fixture present");
    serde_json::from_str(&text).expect("fixture is JSON")
}

fn sep_arcsec(ra1: f64, d1: f64, ra2: f64, d2: f64) -> f64 {
    let u = [d1.cos() * ra1.cos(), d1.cos() * ra1.sin(), d1.sin()];
    let v = [d2.cos() * ra2.cos(), d2.cos() * ra2.sin(), d2.sin()];
    let c = [
        u[1] * v[2] - u[2] * v[1],
        u[2] * v[0] - u[0] * v[2],
        u[0] * v[1] - u[1] * v[0],
    ];
    let s = (c[0] * c[0] + c[1] * c[1] + c[2] * c[2]).sqrt();
    s.atan2(u[0] * v[0] + u[1] * v[1] + u[2] * v[2])
        .to_degrees()
        * 3600.0
}

#[test]
fn the_fixture_star_inputs_are_the_embedded_catalogue_values() {
    let fx = load();
    let cat = skyfix_starfield::catalog().unwrap();
    let stars = fx["stars"].as_array().unwrap();
    assert!(stars.len() >= 300, "{} stars", stars.len());
    for s in stars {
        let hr = s["hr"].as_i64().unwrap() as i32;
        let i = cat
            .index_of_hr(hr)
            .unwrap_or_else(|| panic!("HR {hr} missing"));
        let close = |a: f64, b: f64, tol: f64, what: &str| {
            assert!(
                (a - b).abs() <= tol,
                "HR {hr} {what}: embedded {a}, fixture {b}"
            );
        };
        close(
            cat.ra_j2000_deg[i],
            s["ra_deg"].as_f64().unwrap(),
            1e-8,
            "ra",
        );
        close(
            cat.dec_j2000_deg[i],
            s["dec_deg"].as_f64().unwrap(),
            1e-8,
            "dec",
        );
        close(
            cat.pm_ra_cosdec_mas_yr[i],
            s["pm_ra_cosdec_mas_yr"].as_f64().unwrap(),
            0.0,
            "pm ra",
        );
        close(
            cat.pm_dec_mas_yr[i],
            s["pm_dec_mas_yr"].as_f64().unwrap(),
            0.0,
            "pm dec",
        );
        close(
            cat.parallax_mas[i],
            s["parallax_mas"].as_f64().unwrap(),
            0.0,
            "parallax",
        );
        close(
            f64::from(cat.vmag[i]),
            s["vmag"].as_f64().unwrap(),
            1e-6,
            "vmag",
        );
    }
}

#[test]
fn apparent_places_agree_with_skyfield() {
    let fx = load();
    let cat = skyfix_starfield::catalog().unwrap();
    let mut worst = (0.0f64, String::new());
    let mut sum2 = 0.0;
    let mut n = 0usize;
    for epoch in fx["epochs"].as_array().unwrap() {
        let jd = epoch["jd_utc"].as_f64().unwrap();
        let utc = epoch["utc"].as_str().unwrap();
        let all = skyfix_starfield::apparent_radec_all(jd).unwrap();
        let mut worst_here = 0.0f64;
        for p in epoch["places"].as_array().unwrap() {
            let hr = p[0].as_i64().unwrap() as i32;
            let i = cat.index_of_hr(hr).unwrap();
            let (ra, dec) = (all[2 * i], all[2 * i + 1]);
            let d = sep_arcsec(
                ra,
                dec,
                p[1].as_f64().unwrap().to_radians(),
                p[2].as_f64().unwrap().to_radians(),
            );
            assert!(
                d <= TARGET_ARCSEC,
                "HR {hr} at {utc}: {d:.3}\" from Skyfield (target 0.1')"
            );
            worst_here = worst_here.max(d);
            if d > worst.0 {
                worst = (d, format!("HR {hr} at {utc}"));
            }
            sum2 += d * d;
            n += 1;
        }
        println!("{utc}: worst {worst_here:.4}\"");
    }
    let rms = (sum2 / n as f64).sqrt();
    println!(
        "{n} places: worst {:.4}\" ({:.5}') at {}, rms {rms:.4}\"",
        worst.0,
        worst.0 / 60.0,
        worst.1
    );
    assert!(
        worst.0 <= GUARD_ARCSEC,
        "worst {:.3}\" at {} exceeds the {GUARD_ARCSEC}\" regression guard",
        worst.0,
        worst.1
    );
}
